### ISSUE TITLE
Provide support for Websocket source

### ISSUE THREAD

**Issue by krishnaprasadas** [spring-cloud-stream-app-starters/websocket#2]
As described in  [Stackoverflow](https://stackoverflow.com/questions/46925640/why-there-is-no-websocket-source-available-in-spring-cloud-stream-app-starters-p) there is an interest in providing support for _Websocket source_ especially since there is already a _Websocket sink_

**Comment by sabbyanandan** [comment]
@krishnaprasadas: Looking at the SO discussion, it appears you have close to a working sample in your sandbox. Would you be interested in contributing the `websocket-source`?

**Comment by artembilan** [comment]
The latest progress is here: https://stackoverflow.com/questions/47283166/kafkaproducer-stops-on-application-startup-saying-closing-the-kafka-producer-w.

The related @krishnaprasadas ' code on the matter: https://github.com/krishnaprasadas/websocket/tree/websocket-source/spring-cloud-starter-stream-source-websocket

**Comment by krishnaprasadas** [comment]
Sure, what is the procedure, Can I raise a PR? I haven't used all properties in the source like server port (which can be configured through server.port anyway).

**Comment by artembilan** [comment]
The existing Spring Boot `server.port` is definitely enough. But we should mention it in the README anyway.
There are many other `ServerWebSocketContainer` options to be exposed as configuration properties.

The `payloadType` would be great option as well.

However all of them we can discuss already on the PR or in the separate issues.

Thank you for considering contribution!

**Comment by krishnaprasadas** [comment]
I have created a PR. Please have a look.
